version: '3.8'

services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      - '8081:8080'
    volumes:
      - ./.docker/blazegraph.ini:/RWStore.properties:ro
      - ./data/:/data/:ro
  blazegraph-data:
    image: curlimages/curl:7.76.1
    depends_on:
      - blazegraph
    environment:
      NAMESPACE: "${NAMESPACE:-http://localhost:8080/}"
    entrypoint: ""
    command: ["/wait-for.sh", "blazegraph:8080", "--", "./load-data.sh"]
    volumes:
      - ./.docker/load-data.ini:/load-data.ini:ro
      - ./.docker/load-data.sh:/load-data.sh:ro
      - ./.docker/wait-for.sh:/wait-for.sh:ro
  client:
    build:
      context: client
    environment:
      NAMESPACE: "${NAMESPACE:-http://localhost:8080/}"
      SPARQL_URL: http://blazegraph:8080/bigdata/namespace/kb/sparql
    ports:
      - '8082:8082'
    volumes:
      - ./client/web/:/app/web/:ro
    deploy:
      restart_policy:
        condition: on-failure
  trifid:
    build:
      context: trifid
    ports:
      - '8080:8080'
