version: '3.8'

services:
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    ports:
      - '8081:8080'
    volumes:
      - ./.docker/blazegraph.ini:/RWStore.properties
      - ./.docker/load-data.sh:/load-data.sh
      - ./data/:/data/
  client:
    build:
      context: client
    environment:
      SPARQL_URL: http://blazegraph:8080/bigdata/namespace/kb/sparql
    ports:
      - '8082:8082'
    volumes:
      - ./client/web/:/app/web/
    deploy:
      restart_policy:
        condition: on-failure
  trifid:
    build:
      context: trifid
    ports:
      - '8080:8080'
