version: '3.8'

services:
  client:
    build:
      context: client
    ports:
      - '8082:8082'
    volumes:
      - ./client/web/:/app/web/
    deploy:
      restart_policy:
        condition: on-failure
  jena:
    image: blankdots/jena-fuseki:fuseki4.0.0
    environment:
      ADMIN_PASSWORD: password
    ports:
      - '8081:3030'
    volumes:
      - ./.docker/fuseki.ttl:/data/fuseki/config/config.ttl
      - ./data/:/data/data/
  trifid:
    build:
      context: trifid
    ports:
      - '8080:8080'
